version: '3'
services:
  mongo:
    container_name: my-mongo
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${DockerDataPath}/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aaaaa
  postgres:
    container_name: my-postgres
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${DockerDataPath}/postgresql:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: aaaaa
  redis:
    container_name: my-redis
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${DockerDataPath}/redis/conf:/usr/local/etc/redis
  mysql:
    container_name: my-mysql
    image: "dockerdist.bdmd.com/base/mysql:8.0.16"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${DockerDataPath}/mysql/data:/var/lib/mysql
      - ${DockerDataPath}/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: aaaaa
#     MYSQL_ALLOW_EMPTY_PASSWORD: yes
  mysql-backup:
    container_name: my-mysql-backup
    image: "dockerdist.bdmd.com/base/mysql:8.0.16"
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ${DockerDataPath}/mysql-backup/data:/var/lib/mysql
      - ${DockerDataPath}/mysql-backup/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: aaaaa
#     MYSQL_ALLOW_EMPTY_PASSWORD: yes
  mysql5:
    container_name: my-mysql5
    image: "mysql:5.7"
    restart: always
    ports:
      - "53306:3306"
    volumes:
      - ${DockerDataPath}/mysql5/data:/var/lib/mysql
      - ${DockerDataPath}/mysql5/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: aaaaa
