version: '3'
services:
  mongo:
    container_name: my-mongo
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ${DockerDataPath}/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: aaaaa
  postgres:
    container_name: my-postgres
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${DockerDataPath}/postgresql:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: aaaaa
  redis:
    container_name: my-redis
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ${DockerDataPath}/redis/conf:/usr/local/etc/redis
  mysql:
    # https://hub.docker.com/_/mysql
    container_name: my-mysql
    image: "mysql:latest"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ${DockerDataPath}/mysql/data:/var/lib/mysql
      - ${DockerDataPath}/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: aaaaa
  #   MYSQL_ALLOW_EMPTY_PASSWORD: yes
  rabbit:
    # https://hub.docker.com/_/rabbitmq
    container_name: my-rabbit
    hostname: my-rabbit
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ${DockerDataPath}/rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: aaaaa
